# Generated by Django 5.1 on 2024-08-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emailkasten", "0003_rename_email_id_attachmentmodel_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondentmodel",
            name="email_address",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
