# Generated by Django 5.1 on 2024-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emailkasten", "0006_alter_emailmodel_eml_filepath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentmodel",
            name="file_path",
            field=models.FilePathField(
                max_length=511,
                null=True,
                path="/mnt/archive",
                recursive=True,
                unique=True,
            ),
        ),
    ]
