# Generated by Django 5.1 on 2024-08-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emailkasten", "0009_alter_mailboxmodel_fetching_criterion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailmodel",
            old_name="date_received",
            new_name="datetime",
        ),
        migrations.AddField(
            model_name="emailmodel",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_account",
                to="Emailkasten.accountmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailboxmodel",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("RECENT", "recent"),
                    ("UNSEEN", "unseen"),
                    ("ALL", "all"),
                    ("NEW", "new"),
                    ("DAILY", "daily"),
                ],
                default="RECENT",
                max_length=10,
            ),
        ),
    ]
