# Generated by Django 5.1 on 2024-08-22 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0010_rename_date_received_emailmodel_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_healthy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
