# Generated by Django 5.1 on 2024-08-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0013_alter_emailcorrespondentsmodel_correspondent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
