# Generated by Django 5.1.1 on 2024-09-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0015_accountmodel_created_accountmodel_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailboxmodel',
            name='cycle_interval',
        ),
        migrations.RemoveField(
            model_name='mailboxmodel',
            name='is_fetched',
        ),
        migrations.CreateModel(
            name='DaemonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_interval', models.IntegerField(default=60)),
                ('is_running', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daemon', to='Emailkasten.mailboxmodel')),
            ],
            options={
                'db_table': 'daemons',
            },
        ),
    ]
