# Generated by Django 5.1.1 on 2024-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0016_remove_mailboxmodel_cycle_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='correspondents',
            field=models.ManyToManyField(related_name='emails', through='Emailkasten.EMailCorrespondentsModel', to='Emailkasten.correspondentmodel'),
        ),
    ]
