# Generated by Django 5.1.1 on 2024-09-04 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0017_emailmodel_correspondents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='Emailkasten.accountmodel'),
        ),
    ]
