# Generated by Django 5.1.1 on 2024-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0018_alter_emailmodel_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='prerender_filepath',
            field=models.FilePathField(match='.*\\.jpg$', max_length=255, null=True, path='/mnt/archive', recursive=True),
        ),
    ]
