# Generated by Django 5.1.1 on 2024-10-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0019_emailmodel_prerender_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmodel',
            name='save_images',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FilePathField(max_length=511, null=True, path='/mnt/archive', recursive=True, unique=True)),
                ('datasize', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Emailkasten.emailmodel')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
