# Generated by Django 5.1.1 on 2024-10-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0020_mailboxmodel_save_images_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='inReplyTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='Emailkasten.emailmodel'),
        ),
    ]
