# Generated by Django 5.1.1 on 2024-10-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0021_emailmodel_inreplyto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=255, unique=True)),
                ('list_owner', models.CharField(max_length=255, null=True)),
                ('list_subscribe', models.EmailField(max_length=255, null=True)),
                ('list_unsubscribe', models.EmailField(max_length=255, null=True)),
                ('list_post', models.CharField(max_length=255, null=True)),
                ('list_help', models.CharField(max_length=255, null=True)),
                ('list_archive', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'mailinglists',
            },
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='auto_submitted',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='content_language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='content_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='content_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='delivered_to',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='disposition_notification_to',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='envelope_to',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='importance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='precedence',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='priority',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='reply_to',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='return_path',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='return_receipt_to',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='sender',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='x_originated_client',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='x_priority',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='x_spam',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='mailinglist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='Emailkasten.mailinglistmodel'),
        ),
    ]
