# Generated by Django 5.1.1 on 2024-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0024_emailmodel_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='received',
            field=models.TextField(null=True),
        ),
    ]
