# Generated by Django 5.1 on 2024-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0026_remove_emailmodel_delivered_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_number', models.PositiveIntegerField(unique=True)),
                ('path', models.FilePathField(path='/mnt/archive', unique=True)),
                ('subdirectory_count', models.PositiveSmallIntegerField(default=0)),
                ('current', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'storage',
            },
        ),
    ]
