# Generated by Django 5.1.2 on 2024-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0028_correspondentmodel_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correspondentmodel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailboxmodel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailinglistmodel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
