# Generated by Django 5.1 on 2024-11-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0030_alter_correspondentmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmodel',
            name='is_healthy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailcorrespondentsmodel',
            name='mention',
            field=models.CharField(choices=[('FROM', 'From'), ('TO', 'To'), ('CC', 'Cc'), ('BCC', 'Bcc'), ('SENDER', 'Sender'), ('REPLY_TO', 'Reply-To'), ('RESENT_FROM', 'Resent-From'), ('RESENT_TO', 'Resent-To'), ('RESENT_CC', 'Resent-Cc'), ('RESENT_BCC', 'Resent-Bcc'), ('RESENT_SENDER', 'Resent-Sender'), ('RESENT_REPLY_TO', 'Resent-Reply-To'), ('ENVELOPE_TO', 'Envelope-To'), ('DELIVERED_TO', 'Delivered-To'), ('RETURN_PATH', 'Return-Path'), ('RETURN_RECEIPT_TO', 'Return-Receipt-To'), ('DISPOSITION_NOTIFICATION_TO', 'Disposition-Notification-To')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mailboxmodel',
            name='fetching_criterion',
            field=models.CharField(choices=[('RECENT', 'RECENT'), ('UNSEEN', 'UNSEEN'), ('ALL', 'ALL'), ('NEW', 'NEW'), ('OLD', 'OLD'), ('FLAGGED', 'FLAGGED'), ('DRAFT', 'DRAFT'), ('ANSWERED', 'ANSWERED'), ('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('ANNUALLY', 'ANNUALLY')], default='ALL', max_length=10),
        ),
    ]
