# Generated by Django 5.1 on 2024-11-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0031_mailboxmodel_is_healthy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemonmodel',
            name='log_filepath',
            field=models.FilePathField(null=True, recursive=True),
        ),
    ]
