# Generated by Django 5.1 on 2024-11-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0032_daemonmodel_log_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemonmodel',
            name='is_healthy',
            field=models.BooleanField(default=True),
        ),
    ]
