# Generated by Django 5.1.4 on 2025-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0037_alter_accountmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemonmodel',
            name='restart_time',
            field=models.IntegerField(default=10),
        ),
    ]
