# Generated by Django 5.2.5 on 2025-09-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_delete_storageshard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbox",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite"),
        ),
    ]
