# Generated by Django 5.2.5 on 2025-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_mailbox_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_error",
            field=models.TextField(blank=True, default="", verbose_name="last error"),
        ),
        migrations.AddField(
            model_name="account",
            name="last_error_occurred_at",
            field=models.DateTimeField(
                null=True, verbose_name="time of last error occurrence"
            ),
        ),
        migrations.AddField(
            model_name="daemon",
            name="last_error_occurred_at",
            field=models.DateTimeField(
                null=True, verbose_name="time of last error occurrence"
            ),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="last_error",
            field=models.TextField(blank=True, default="", verbose_name="last error"),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="last_error_occurred_at",
            field=models.DateTimeField(
                null=True, verbose_name="time of last error occurrence"
            ),
        ),
    ]
